### ISSUE TITLE
Support for ignoring certain files

### ISSUE THREAD

**Issue by jordond** [contra/gulp-cached#14]
I am currently using gulp-cached with typescript so that I can speed up the compilation of my code.

However the index of my application references a `dts.d.ts` file, which is the source definitions for the compiler.  And since this file never changes, it is never processed by gulp-cached, which causes the compiler to break down and not work.

Now I could add a reference to my `dts.d.ts` file in every single one of my source files, but that is tedious and annoying.  So I currently use a hacky way to always process the definition file.

```javascript
var cache = $.cached.caches['compile-typescript'];
 if (cache) {
   delete cache[''typings/dts.d.ts']
 }
```

It works, but It would be nice if I could just pass that file to gulp-cached so it will always allow it through.

**Comment by contra** [comment]
Use the `gulp-if` plugin to solve this

**Comment by contra** [comment]
```js
.pipe(gif('!typings/dts.d.ts', cache('stuff')))
```
