### ISSUE TITLE
nothing in cache

### ISSUE THREAD

**Issue by raphaelgoetter** [contra/gulp-cached#16]
Hello,

I'm testing gulp-cached for my imagemin task : 

```
gulp.task('img', function () {
  return gulp.src(source + imgFiles)
    .pipe(cache('images'))
    .pipe(plugins.imagemin({
      svgoPlugins: [{
        removeViewBox: false
      }, {
        cleanupIDs: false
      }]
    }))
    .pipe(gulp.dest(destination + 'assets/'));
});
```

I'm testing with 2 png files.

Each time I run the task, every files is optimised : 

> `gulp-imagemin: Minified 2 images (saved 27.44 kB - 44.5%)`

Is there a problem with my task ?

**Comment by contra** [comment]
Haven't tested on binary files, this is probably the problem: https://github.com/contra/gulp-cached/blob/master/index.js#L23

**Comment by soulcreate** [comment]
+1

**Comment by Nitin-Prabhakar** [comment]
Nothing is written to cache

My task:

> ```
> var optimizeStyles = function(src) {
>      return $.src(src)
>         //compares modified times of the path passed, and the files from src.
>         //By default, if any single file has a modified timestamp lesser than the
>         //file on the path passed,not only that file, but the all files from src
>         //will be passed downstream.
>         //.pipe($$.newer('build/css/app.css'))
>         .pipe($$.cached('styles'))
>         //concatenate all files - build to app.css
>         //app.js is truncated before concatenation
>         .pipe($$.concat('app.css'))
>         .pipe($.dest('build/css'))
>         //minify app.css
>         .pipe($$.cleanCss(function(file) {
>             console.log('minifying : ' + file.path);
>         }))
>         //add suffix
>         .pipe($$.rename({
>             'suffix': '.min'
>         }))
>         .pipe($.dest('build/css'));
> }
> 
> ```

cache workers:

> ```
> 
> var clearCache = function(){
>     return $$.cached.caches = {};
> }
> 
> var viewCache = function(){
>     console.log($$.cached.caches)
> }
> ```

after running optimizeStyles, 
if  I view the cache, it is empty

**Comment by contra** [comment]
People having issues with this: can you create a **minimal** sample repository that reproduces the problem?

**Comment by Nitin-Prabhakar** [comment]
Here you go

https://github.com/Nitin-Prabhakar/gulp-cached.git

**Comment by contra** [comment]
@Nitin-Prabhakar There's quite a bit going on in that gulpfile, could you reduce it even further? Using no other plugins would be ideal

**Comment by Nitin-Prabhakar** [comment]
Done @contra 
I have limited it to gulp-cached and gulp-concat Nothing else
Even the package.json is now minimal.

**Comment by contra** [comment]
@Nitin-Prabhakar Your problem is that you are running `viewCache()` before any files have been read. gulp runs tasks in parallel by default.

https://github.com/Nitin-Prabhakar/gulp-cached/blob/master/gulpfile.js#L84 is running two things at the same time, not in order

**Comment by Nitin-Prabhakar** [comment]
@contra you can check by individually running them one after another as well

it just doesn't cache

If I understand right, then once you run **optimizeStyles** , 

the cache should be built because it is the first run

so on running **viewCache** after **optimizeStyles**, I should be able to log the cache entries

**Comment by Nitin-Prabhakar** [comment]
![screenshot from 2016-05-02 23 53 02](https://cloud.githubusercontent.com/assets/15086525/14963408/21f84460-10c1-11e6-84da-d9c0f30a7fdd.png)

**Comment by contra** [comment]
@Nitin-Prabhakar Looking into it, thanks for the extra info!

**Comment by contra** [comment]
@Nitin-Prabhakar Running `viewCache` after `optimiseStyles` has been completed yields the correct output:

![image](https://cloud.githubusercontent.com/assets/425716/14965297/aa9fa1d8-107a-11e6-89ac-805f7c90ed77.png)

**Comment by Nitin-Prabhakar** [comment]
Still doesnt work for me! ....

Strange! verry strange

**Comment by Nitin-Prabhakar** [comment]
@contra 
I am out of ideas as to why it doesn't work for me.
Am I doing something wrong in the task I have written?

would node versions and dependency versions or vinyl fs versions be an issue?
Just cant get it to work

**Comment by contra** [comment]
@Nitin-Prabhakar You are running `optimizeStyles`, then the process dies. Then you start a *new* gulp process and run `viewCache` which prints nothing, because there is no cache. It doesn't persist between new processes. It's an in-memory object that goes away when the process dies.

The cache is working fine - run optimizeStyles and viewCache on the same run and it will print the same thing I just linked you.

**Comment by Nitin-Prabhakar** [comment]
TYSM! gotcha. :+1: :+1: :+1:
